name: Production Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      # 1. Берем код без самоуправства
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          clean: false  # Не трогаем существующие файлы
          fetch-depth: 0

      # 2. Умная очистка (только что нужно)
      - name: Clean workspace
        run: |
          # Удаляем всё, кроме папки deploy
          find "$GITHUB_WORKSPACE" -mindepth 1 -maxdepth 1 \
            ! -name 'deploy' \
            -exec rm -rf {} +
          
          # Внутри deploy оставляем только нужное
          find "$GITHUB_WORKSPACE/deploy" -mindepth 1 \
            ! -name 'postgres_data' \
            ! -name 'docker-compose.yml' \
            ! -name '*.env' \
            -exec rm -rf {} +

      # 3. Запуск с пересборкой
      - name: Deploy containers
        working-directory: ./deploy
        run: |
          docker-compose down -v --remove-orphans
          docker-compose up -d --build --force-recreate
          docker-compose ps