// Code generated by MockGen. DO NOT EDIT.
// Source: post.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPostRepo is a mock of PostRepo interface.
type MockPostRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPostRepoMockRecorder
}

// MockPostRepoMockRecorder is the mock recorder for MockPostRepo.
type MockPostRepoMockRecorder struct {
	mock *MockPostRepo
}

// NewMockPostRepo creates a new mock instance.
func NewMockPostRepo(ctrl *gomock.Controller) *MockPostRepo {
	mock := &MockPostRepo{ctrl: ctrl}
	mock.recorder = &MockPostRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostRepo) EXPECT() *MockPostRepoMockRecorder {
	return m.recorder
}

// PostForm mocks base method.
func (m *MockPostRepo) PostForm(ctx context.Context, institutionId int, info []string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostForm", ctx, institutionId, info)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostForm indicates an expected call of PostForm.
func (mr *MockPostRepoMockRecorder) PostForm(ctx, institutionId, info interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostForm", reflect.TypeOf((*MockPostRepo)(nil).PostForm), ctx, institutionId, info)
}

// PostInstitution mocks base method.
func (m *MockPostRepo) PostInstitution(ctx context.Context, name string, inn int, columns []string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostInstitution", ctx, name, inn, columns)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostInstitution indicates an expected call of PostInstitution.
func (mr *MockPostRepoMockRecorder) PostInstitution(ctx, name, inn, columns interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostInstitution", reflect.TypeOf((*MockPostRepo)(nil).PostInstitution), ctx, name, inn, columns)
}

// PostMentor mocks base method.
func (m *MockPostRepo) PostMentor(ctx context.Context, name string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostMentor", ctx, name)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostMentor indicates an expected call of PostMentor.
func (mr *MockPostRepoMockRecorder) PostMentor(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostMentor", reflect.TypeOf((*MockPostRepo)(nil).PostMentor), ctx, name)
}
