// Code generated by MockGen. DO NOT EDIT.
// Source: delete.go

// Package delete is a generated GoMock package.
package delete

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDeleter is a mock of Deleter interface.
type MockDeleter struct {
	ctrl     *gomock.Controller
	recorder *MockDeleterMockRecorder
}

// MockDeleterMockRecorder is the mock recorder for MockDeleter.
type MockDeleterMockRecorder struct {
	mock *MockDeleter
}

// NewMockDeleter creates a new mock instance.
func NewMockDeleter(ctrl *gomock.Controller) *MockDeleter {
	mock := &MockDeleter{ctrl: ctrl}
	mock.recorder = &MockDeleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleter) EXPECT() *MockDeleterMockRecorder {
	return m.recorder
}

// DeleteInstitution mocks base method.
func (m *MockDeleter) DeleteInstitution(ctx context.Context, institutionId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInstitution", ctx, institutionId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInstitution indicates an expected call of DeleteInstitution.
func (mr *MockDeleterMockRecorder) DeleteInstitution(ctx, institutionId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInstitution", reflect.TypeOf((*MockDeleter)(nil).DeleteInstitution), ctx, institutionId)
}

// DeleteMentor mocks base method.
func (m *MockDeleter) DeleteMentor(ctx context.Context, mentorId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMentor", ctx, mentorId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMentor indicates an expected call of DeleteMentor.
func (mr *MockDeleterMockRecorder) DeleteMentor(ctx, mentorId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMentor", reflect.TypeOf((*MockDeleter)(nil).DeleteMentor), ctx, mentorId)
}
