// Code generated by MockGen. DO NOT EDIT.
// Source: post.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPost is a mock of Post interface.
type MockPost struct {
	ctrl     *gomock.Controller
	recorder *MockPostMockRecorder
}

// MockPostMockRecorder is the mock recorder for MockPost.
type MockPostMockRecorder struct {
	mock *MockPost
}

// NewMockPost creates a new mock instance.
func NewMockPost(ctrl *gomock.Controller) *MockPost {
	mock := &MockPost{ctrl: ctrl}
	mock.recorder = &MockPostMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPost) EXPECT() *MockPostMockRecorder {
	return m.recorder
}

// PostForm mocks base method.
func (m *MockPost) PostForm(ctx context.Context, info []string, institutionId int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostForm", ctx, info, institutionId)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostForm indicates an expected call of PostForm.
func (mr *MockPostMockRecorder) PostForm(ctx, info, institutionId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostForm", reflect.TypeOf((*MockPost)(nil).PostForm), ctx, info, institutionId)
}

// PostInstitution mocks base method.
func (m *MockPost) PostInstitution(ctx context.Context, name string, inn int, columns []string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostInstitution", ctx, name, inn, columns)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostInstitution indicates an expected call of PostInstitution.
func (mr *MockPostMockRecorder) PostInstitution(ctx, name, inn, columns interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostInstitution", reflect.TypeOf((*MockPost)(nil).PostInstitution), ctx, name, inn, columns)
}

// PostMentor mocks base method.
func (m *MockPost) PostMentor(ctx context.Context, name string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostMentor", ctx, name)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostMentor indicates an expected call of PostMentor.
func (mr *MockPostMockRecorder) PostMentor(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostMentor", reflect.TypeOf((*MockPost)(nil).PostMentor), ctx, name)
}

// MockGet is a mock of Get interface.
type MockGet struct {
	ctrl     *gomock.Controller
	recorder *MockGetMockRecorder
}

// MockGetMockRecorder is the mock recorder for MockGet.
type MockGetMockRecorder struct {
	mock *MockGet
}

// NewMockGet creates a new mock instance.
func NewMockGet(ctrl *gomock.Controller) *MockGet {
	mock := &MockGet{ctrl: ctrl}
	mock.recorder = &MockGetMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGet) EXPECT() *MockGetMockRecorder {
	return m.recorder
}

// GetFormColumns mocks base method.
func (m *MockGet) GetFormColumns(ctx context.Context, id int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFormColumns", ctx, id)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFormColumns indicates an expected call of GetFormColumns.
func (mr *MockGetMockRecorder) GetFormColumns(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFormColumns", reflect.TypeOf((*MockGet)(nil).GetFormColumns), ctx, id)
}

// MockPoster is a mock of Poster interface.
type MockPoster struct {
	ctrl     *gomock.Controller
	recorder *MockPosterMockRecorder
}

// MockPosterMockRecorder is the mock recorder for MockPoster.
type MockPosterMockRecorder struct {
	mock *MockPoster
}

// NewMockPoster creates a new mock instance.
func NewMockPoster(ctrl *gomock.Controller) *MockPoster {
	mock := &MockPoster{ctrl: ctrl}
	mock.recorder = &MockPosterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPoster) EXPECT() *MockPosterMockRecorder {
	return m.recorder
}

// GetFormColumns mocks base method.
func (m *MockPoster) GetFormColumns(ctx context.Context, id int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFormColumns", ctx, id)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFormColumns indicates an expected call of GetFormColumns.
func (mr *MockPosterMockRecorder) GetFormColumns(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFormColumns", reflect.TypeOf((*MockPoster)(nil).GetFormColumns), ctx, id)
}

// PostForm mocks base method.
func (m *MockPoster) PostForm(ctx context.Context, info []string, institutionId int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostForm", ctx, info, institutionId)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostForm indicates an expected call of PostForm.
func (mr *MockPosterMockRecorder) PostForm(ctx, info, institutionId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostForm", reflect.TypeOf((*MockPoster)(nil).PostForm), ctx, info, institutionId)
}

// PostInstitution mocks base method.
func (m *MockPoster) PostInstitution(ctx context.Context, name string, inn int, columns []string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostInstitution", ctx, name, inn, columns)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostInstitution indicates an expected call of PostInstitution.
func (mr *MockPosterMockRecorder) PostInstitution(ctx, name, inn, columns interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostInstitution", reflect.TypeOf((*MockPoster)(nil).PostInstitution), ctx, name, inn, columns)
}

// PostMentor mocks base method.
func (m *MockPoster) PostMentor(ctx context.Context, name string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostMentor", ctx, name)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostMentor indicates an expected call of PostMentor.
func (mr *MockPosterMockRecorder) PostMentor(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostMentor", reflect.TypeOf((*MockPoster)(nil).PostMentor), ctx, name)
}
