// Code generated by MockGen. DO NOT EDIT.
// Source: get.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	entities "forms/internal/entities"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockGetter is a mock of Getter interface.
type MockGetter struct {
	ctrl     *gomock.Controller
	recorder *MockGetterMockRecorder
}

// MockGetterMockRecorder is the mock recorder for MockGetter.
type MockGetterMockRecorder struct {
	mock *MockGetter
}

// NewMockGetter creates a new mock instance.
func NewMockGetter(ctrl *gomock.Controller) *MockGetter {
	mock := &MockGetter{ctrl: ctrl}
	mock.recorder = &MockGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetter) EXPECT() *MockGetterMockRecorder {
	return m.recorder
}

// GetFormColumns mocks base method.
func (m *MockGetter) GetFormColumns(ctx context.Context, id int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFormColumns", ctx, id)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFormColumns indicates an expected call of GetFormColumns.
func (mr *MockGetterMockRecorder) GetFormColumns(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFormColumns", reflect.TypeOf((*MockGetter)(nil).GetFormColumns), ctx, id)
}

// GetInstitutionFromINN mocks base method.
func (m *MockGetter) GetInstitutionFromINN(ctx context.Context, inn int) (entities.Institution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstitutionFromINN", ctx, inn)
	ret0, _ := ret[0].(entities.Institution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInstitutionFromINN indicates an expected call of GetInstitutionFromINN.
func (mr *MockGetterMockRecorder) GetInstitutionFromINN(ctx, inn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstitutionFromINN", reflect.TypeOf((*MockGetter)(nil).GetInstitutionFromINN), ctx, inn)
}

// GetInstitutions mocks base method.
func (m *MockGetter) GetInstitutions(ctx context.Context) ([]entities.Institution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstitutions", ctx)
	ret0, _ := ret[0].([]entities.Institution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInstitutions indicates an expected call of GetInstitutions.
func (mr *MockGetterMockRecorder) GetInstitutions(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstitutions", reflect.TypeOf((*MockGetter)(nil).GetInstitutions), ctx)
}

// GetMentors mocks base method.
func (m *MockGetter) GetMentors(ctx context.Context) ([]entities.Mentor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMentors", ctx)
	ret0, _ := ret[0].([]entities.Mentor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMentors indicates an expected call of GetMentors.
func (mr *MockGetterMockRecorder) GetMentors(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMentors", reflect.TypeOf((*MockGetter)(nil).GetMentors), ctx)
}
