name: Docker Compose Deployment

on:
  push:
    branches: [main]


jobs:
  deploy:
    runs-on: self-hosted
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Deploy services
        working-directory: ./deploy
        run: |
          docker-compose pull
          docker-compose up -d --build
          sleep 30
          docker-compose ps -a
          docker-compose logs --tail=20

      - name: Verify services
        working-directory: ./deploy
        run: |
          curl -I http://localhost/forms/ || echo "Nginx not responding"