name: Docker Compose Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    timeout-minutes: 30

    steps:
      - name: Checkout без ебучей очистки
        uses: actions/checkout@v4
        with:
          repository: TATAROmangol/npc_ric
          clean: false  # чтобы не трогал мои файлы
          fetch-depth: 0

      - name: Чистка только того, что надо
        run: |
          # Блядский workaround для ебанного runner'а
          cd /home/github-runner/actions-runner/_work/npc_ric/npc_ric
          
          # Удаляем всё, кроме папки deploy
          find . -mindepth 1 -maxdepth 1 -not -name 'deploy' -exec rm -rf {} +
          
          # Чистим внутри deploy, кроме postgres_data
          cd deploy
          find . -mindepth 1 -not -name 'postgres_data' -not -name 'docker-compose.yml' -exec rm -rf {} +

      - name: Деплой без пиздежа
        working-directory: ./deploy
        run: |
          docker-compose down --remove-orphans --volumes --timeout 30 || true
          docker-compose up -d --build --force-recreate
          sleep 30
          docker-compose ps -a