name: Docker Compose CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: deploy/docker-compose.yml
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
        
    - name: Install Docker Compose
      run: |
        curl -fsSL https://github.com/docker/compose/releases/download/v2.20.3/docker-compose-linux-x86_64 -o docker-compose
        chmod +x docker-compose
        sudo mv docker-compose /usr/local/bin/
        
    - name: Build and deploy
      working-directory: ../../deploy  # Все команды выполняем из папки deploy
      run: |
        docker-compose pull
        docker-compose up -d --build
        docker-compose ps
