name: Docker Compose Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: TATAROmangol/npc_ric
          clean: false

      - name: Fix permissions (sudo)
        run: |
          cd /home/github-runner/actions-runner/_work/npc_ric/npc_ric
          sudo chown -R $USER:$USER ./deploy/postgres_data || true
          sudo chmod -R 755 ./deploy/postgres_data || true

      - name: Clean workspace
        run: |
          cd /home/github-runner/actions-runner/_work/npc_ric/npc_ric
          find . -mindepth 1 -not -path './deploy/postgres_data*' -exec rm -rf {} + 2>/dev/null || true

      - name: Deploy services
        working-directory: ./deploy
        run: |
          docker-compose down --remove-orphans --volumes --timeout 30 || true
          docker system prune -a -f || true
          docker-compose up -d --build --force-recreate
          sleep 30
          docker-compose ps -a