name: Docker Compose Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    timeout-minutes: 30

    steps:
      - name: Checkout code (без очистки)
        uses: actions/checkout@v4
        with:
          repository: TATAROmangol/npc_ric
          clean: false
          fetch-depth: 0

      - name: Prepare environment
        run: |
          WORKSPACE="/home/github-runner/actions-runner/_work/npc_ric/npc_ric"
          
          # Устанавливаем правильные права
          sudo chown -R github-runner:github-runner "$WORKSPACE"
          sudo chmod -R 775 "$WORKSPACE"

          # Очищаем всё, кроме нужных папок
          cd "$WORKSPACE"
          find . -mindepth 1 \
            -not -path './deploy' \
            -not -path './deploy/postgres_data*' \
            -exec sudo rm -rf {} + 2>/dev/null || true

      - name: Clean Docker environment
        run: |
          # Полная очистка Docker
          docker-compose -f ./deploy/docker-compose.yml down --remove-orphans --volumes --timeout 30 || true
          docker system prune -a -f || true

      - name: Deploy services
        working-directory: ./deploy
        run: |
          docker-compose up -d --build --force-recreate
          sleep 30
          docker-compose ps -a
          docker logs auth  # Для отладки