name: Production Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      # 1. Забираем код (без лишней очистки)
      - name: Получить код
        uses: actions/checkout@v4
        with:
          clean: true  # Полностью чистая копия
          fetch-depth: 0  # Полная история коммитов

      # 2. Настраиваем права (без sudo, если возможно)
      - name: Установить права
        run: |
          chmod -R 775 . || true
          chown -R $USER:$USER . || true

      # 3. Развертывание контейнеров
      - name: Запуск контейнеров
        working-directory: ./deploy
        run: |
          # Останавливаем и удаляем старые контейнеры
          docker-compose down -v --remove-orphans || true
          
          # Собираем и запускаем новые контейнеры
          docker-compose up -d --build --force-recreate
          
          # Проверяем статус
          docker-compose ps
          docker ps -a