name: Production Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      # 1. Отключаем автоматическую очистку
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          clean: false  # Важно: отключаем встроенную очистку
          persist-credentials: false

      # 2. Вручную очищаем только нужные части
      - name: Custom clean
        run: |
          WORKSPACE="/home/github-runner/actions-runner/_work/npc_ric/npc_ric"
          
          # Даем права на всю папку (если нужно)
          sudo chown -R $USER:$USER "$WORKSPACE" || true
          sudo chmod -R 775 "$WORKSPACE" || true

          # Удаляем всё, кроме папки deploy
          find "$WORKSPACE" -mindepth 1 -maxdepth 1 \
            ! -path "$WORKSPACE/deploy" \
            -exec sudo rm -rf {} + || true

          # Внутри deploy оставляем только нужное
          find "$WORKSPACE/deploy" -mindepth 1 \
            ! -path "$WORKSPACE/deploy/postgres_data*" \
            ! -path "$WORKSPACE/deploy/docker-compose*" \
            ! -path "$WORKSPACE/deploy/*.env" \
            -exec sudo rm -rf {} + || true

      # 3. Полная пересборка контейнеров
      - name: Deploy containers
        working-directory: ./deploy
        run: |
          docker-compose down -v --remove-orphans || true
          docker-compose up -d --build --force-recreate
          docker-compose ps