name: Docker Compose Deployment

on:
  push:
    branches: [main]
    paths:
      - 'deploy/**'
      - '.github/workflows/**'

jobs:
  deploy:
    runs-on: self-hosted
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout

      - name: Setup Docker
        uses: docker/setup-buildx-action

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Deploy services
        working-directory: ./deploy
        run: |
          docker-compose pull
          docker-compose up -d --build
          sleep 30  # Даем время сервисам запуститься
          docker-compose ps -a
          docker-compose logs --tail=20

      - name: Verify services
        working-directory: ./deploy
        run: |
          # Проверка Nginx
          curl -I http://localhost/forms/ || echo "Nginx not responding"