name: Docker Compose Deployment

on:
  push:
    branches: [main]
    

jobs:
  deploy:
    runs-on: self-hosted
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          buildkitd-flags: --allow-insecure-entitlement security.insecure

      - name: Deploy services
        working-directory: ./deploy
        run: |
          docker buildx build \
          --cache-from type=gha \
          --cache-to type=gha,mode=max \
          -t deploy \
          .

      - name: Verify services
        working-directory: ./deploy
        run: |
          curl -I http://localhost/forms/ || echo "Nginx not responding"