name: Docker Compose Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: TATAROmangol/npc_ric
          clean: false

      - name: Prepare workspace
        run: |
          cd /home/github-runner/actions-runner/_work/npc_ric/npc_ric
          sudo chmod -R 777 ./deploy/postgres_data || true
          find . -mindepth 1 -not -path './deploy/postgres_data*' -delete 2>/dev/null || true

      - name: Deploy services
        working-directory: ./deploy
        run: |
          docker-compose down -v || true
          docker-compose up -d --build
          sleep 30
          docker-compose ps -a