name: Docker Compose CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
        
    - name: Install Docker Compose
      run: |
        curl -fsSL https://github.com/docker/compose/releases/download/v2.20.3/docker-compose-linux-x86_64 -o docker-compose
        chmod +x docker-compose
        sudo mv docker-compose /usr/local/bin/
        
    - name: Build and deploy
      working-directory: ./deploy  # Переходим в папку deploy
      run: |
        # Ensure environment variables are set
        docker-compose -f docker-compose.yml pull
        docker-compose -f docker-compose.yml up -d --build
        docker-compose -f docker-compose.yml ps
        docker logs nginx
